from flask import Blueprint, request, jsonify, current_app
import os
from datetime import datetime
from werkzeug.utils import secure_filename
from app.data_loader import transform_bookings_to_daily_occupancy, enrich_daily_occupancy_with_calendar
from app.model import train_and_forecast_sarimax

api_bp = Blueprint('api', __name__, url_prefix='/api')

@api_bp.route('/forecast', methods=['POST'])
def forecast():
    """
    API endpoint for uploading CSV and generating forecast.
    
    Request:
        - file: CSV file (multipart/form-data)
        - forecast_horizon: Number of days to forecast (optional, default: 60)
    
    Response:
        {
            "success": true,
            "historical": [...],  // Last 30 days
            "forecast": [...],    // Forecast data
            "stats": {
                "total_days": int,
                "occupied_days": int,
                "occupancy_rate": float,
                "avg_forecast_occupancy": float,
                "forecast_days": int
            }
        }
    """
    # Check if file was uploaded
    if 'file' not in request.files:
        return jsonify({'success': False, 'error': 'No file uploaded'}), 400
    
    file = request.files['file']
    
    if file.filename == '':
        return jsonify({'success': False, 'error': 'No file selected'}), 400
    
    if not file.filename.endswith('.csv'):
        return jsonify({'success': False, 'error': 'File must be a CSV'}), 400
    
    try:
        # Get forecast horizon parameter (default 60)
        forecast_horizon = int(request.form.get('forecast_horizon', 60))
        forecast_horizon = max(30, min(90, forecast_horizon))  # Clamp between 30-90
        
        # Save uploaded file
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = secure_filename(f'bookings_{timestamp}.csv')
        filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
        file.save(filepath)
        
        # Transform bookings to daily occupancy
        daily_occupancy = transform_bookings_to_daily_occupancy(
            filepath=filepath,
            output_dir='data/processed'
        )
        
        # Enrich with Chilean calendar context
        occupancy_filepath = os.path.join('data/processed', f'bookings_daily_occupancy_{datetime.now().strftime("%Y%m%d")}.csv')
        calendar_filepath = 'data/special_days_cl_2022_2040.csv'
        enriched_data = enrich_daily_occupancy_with_calendar(
            occupancy_filepath=occupancy_filepath,
            calendar_filepath=calendar_filepath,
            output_dir='data/processed'
        )
        
        # Path to features file (generated by enrich function)
        features_filepath = os.path.join('data/processed', f'features_daily_{datetime.now().strftime("%Y%m%d")}.csv')
        
        # Train SARIMAX model and forecast
        forecast_df = train_and_forecast_sarimax(
            features_filepath=features_filepath,
            forecast_horizon=forecast_horizon,
            output_dir='data/outputs'
        )
        
        # Prepare historical data (last 30 days)
        historical = enriched_data.tail(30)
        
        # Convert dates to ISO format for JSON
        historical_data = historical.copy()
        historical_data['ds'] = historical_data['ds'].dt.strftime('%Y-%m-%d')
        historical_list = historical_data.to_dict('records')
        
        forecast_data = forecast_df.copy()
        forecast_data['ds'] = forecast_data['ds'].dt.strftime('%Y-%m-%d')
        forecast_list = forecast_data.to_dict('records')
        
        # Calculate statistics
        total_days = len(enriched_data)
        occupied_days = int(enriched_data['y'].sum())
        occupancy_rate = (occupied_days / total_days * 100) if total_days > 0 else 0
        avg_forecast_occupancy = float(forecast_df['yhat'].mean() * 100)
        
        # Count special days in forecast period
        holidays_in_forecast = int(forecast_df['is_holiday'].sum())
        sandwiches_in_forecast = int(forecast_df['is_sandwich'].sum())
        weekends_in_forecast = int(forecast_df['is_weekend'].sum())
        
        return jsonify({
            'success': True,
            'historical': historical_list,
            'forecast': forecast_list,
            'stats': {
                'total_days': total_days,
                'occupied_days': occupied_days,
                'occupancy_rate': round(occupancy_rate, 1),
                'avg_forecast_occupancy': round(avg_forecast_occupancy, 1),
                'forecast_days': len(forecast_df),
                'holidays_in_forecast': holidays_in_forecast,
                'sandwiches_in_forecast': sandwiches_in_forecast,
                'weekends_in_forecast': weekends_in_forecast
            }
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


@api_bp.route('/health', methods=['GET'])
def health():
    """Health check endpoint"""
    return jsonify({
        'status': 'healthy',
        'service': 'refuge-occupancy-forecasting',
        'version': '1.0.0'
    })
