from flask import Blueprint, render_template, request, current_app
import os
from datetime import datetime
from app.data_loader import transform_bookings_to_daily_occupancy, enrich_daily_occupancy_with_calendar
from app.model import train_and_forecast_sarimax
from app.comparison import run_comparison

bp = Blueprint('main', __name__)

@bp.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        # Check if file was uploaded
        if 'file' not in request.files:
            return render_template('index.html', error='No file uploaded')
        
        file = request.files['file']
        
        if file.filename == '':
            return render_template('index.html', error='No file selected')
        
        if not file.filename.endswith('.csv'):
            return render_template('index.html', error='File must be a CSV')
        
        try:
            # Save uploaded file
            timestamp = datetime.now().strftime('%Y%m%d')
            filename = f'bookings_{timestamp}.csv'
            filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            file.save(filepath)
            
            # Transform bookings to daily occupancy
            daily_occupancy = transform_bookings_to_daily_occupancy(
                filepath=filepath,
                output_dir='data/processed'
            )
            
            # Enrich with Chilean calendar context
            occupancy_filepath = os.path.join('data/processed', f'bookings_daily_occupancy_{timestamp}.csv')
            calendar_filepath = 'data/special_days_cl_2022_2040.csv'
            enriched_data = enrich_daily_occupancy_with_calendar(
                occupancy_filepath=occupancy_filepath,
                calendar_filepath=calendar_filepath,
                output_dir='data/processed'
            )
            
            # Path to features file (generated by enrich function)
            features_filepath = os.path.join('data/processed', f'features_daily_{timestamp}.csv')
            
            # Train SARIMAX model and forecast 60 days
            forecast_df = train_and_forecast_sarimax(
                features_filepath=features_filepath,
                forecast_horizon=60,
                output_dir='data/outputs'
            )
            
            # Prepare historical data (last 30 days)
            historical = enriched_data.tail(30)
            
            # Convert to list of dicts for template
            forecast_data = forecast_df.to_dict('records')
            historical_data = historical.to_dict('records')
            
            # Statistics for display
            total_days = len(enriched_data)
            occupied_days = int(enriched_data['y'].sum())
            occupancy_rate = (occupied_days / total_days * 100) if total_days > 0 else 0
            avg_forecast_occupancy = forecast_df['yhat'].mean() * 100
            
            return render_template(
                'index.html',
                forecast=forecast_data,
                historical=historical_data,
                total_days=total_days,
                occupied_days=occupied_days,
                occupancy_rate=occupancy_rate,
                avg_forecast_occupancy=avg_forecast_occupancy,
                forecast_days=len(forecast_df),
                success=True
            )
            
        except Exception as e:
            return render_template('index.html', error=f'Error processing file: {str(e)}')
    
    return render_template('index.html')


@bp.route('/compare', methods=['POST'])
def compare():
    """Upload real booking data and compare against the latest forecast."""
    if 'actual_file' not in request.files:
        return render_template('index.html', compare_error='No se subió ningún archivo de datos reales.')

    file = request.files['actual_file']

    if file.filename == '':
        return render_template('index.html', compare_error='No se seleccionó ningún archivo.')

    if not file.filename.lower().endswith('.csv'):
        return render_template('index.html', compare_error='El archivo debe ser un CSV.')

    try:
        from werkzeug.utils import secure_filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'actuals_upload_{timestamp}.csv'
        filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
        file.save(filepath)

        comparison_df, metrics = run_comparison(
            booking_filepath=filepath,
            outputs_dir='data/outputs',
            processed_dir='data/processed',
        )

        comparison_data = comparison_df.to_dict('records')

        return render_template(
            'index.html',
            comparison=comparison_data,
            metrics=metrics,
            compare_success=True,
        )

    except (FileNotFoundError, ValueError) as e:
        return render_template('index.html', compare_error=str(e))
    except Exception as e:
        return render_template('index.html', compare_error=f'Error inesperado: {str(e)}')
